export const ALERT_MESSAGE_SUCCESS = "ALERT_MESSAGE_SUCCESS";
export const ALERT_MESSAGE_WARNING = "ALERT_MESSAGE_WARNING";
export const ALERT_MESSAGE_ERROR = "ALERT_MESSAGE_ERROR";
export const ALERT_MESSAGE_REMOVE_AT = "ALERT_MESSAGE_REMOVE_AT";
export const ALERT_MESSAGE_CLEAR_ALL = "ALERT_MESSAGE_CLEAR_ALL";

export enum ALERT_MESSAGE {
  SUCCESS = "ALERT_MESSAGE_SUCCESS",
  WARNING = "ALERT_MESSAGE_WARNING",
  ERROR = "ALERT_MESSAGE_ERROR",
  REMOVE_AT = "ALERT_MESSAGE_REMOVE_AT",
  CLEAR_ALL = "ALERT_MESSAGE_CLEAR_ALL"
}
