export enum ALERT_MESSAGE {
  SUCCESS = "ALERT_MESSAGE_SUCCESS",
  WARNING = "ALERT_MESSAGE_WARNING",
  ERROR = "ALERT_MESSAGE_ERROR",
  REMOVE_AT = "ALERT_MESSAGE_REMOVE_AT",
  CLEAR_ALL = "ALERT_MESSAGE_CLEAR_ALL"
}
