export enum EVENT_LOGO_TYPE {
  All = "All",
  ASSET_STARTED = "AssetStarted",
  ASSET_FINISHED = "AssetFinished",
  PROGRAM_PERIOD_STARTS = "ProgramPeriodStarts",
  PROGRAM_PERIOD_ENDS = "ProgramPeriodEnds",
  INVESTOR_INVEST = "InvestorInvest",
  INVESTOR_WITHDRAW = "InvestorWithdraw",
  MANAGER_INVEST = "ManagerInvest",
  MANAGER_WITHDRAW = "ManagerWithdraw",
  entranceFee = "EntranceFee",
  EXIT_FEE = "ExitFee",
  PROFIT = "Profit",
  LOSS = "Loss",
  REINVEST = "Reinvest",
  CANCELLED = "Cancelled",
  CANCELLED_RED = "CancelledRed",
  INVEST = "Invest",
  WITHDRAW = "Withdraw",
  STARTED = "Started",
  ENDED = "Ended",
  ENDED_RED = "EndedRed"
}
